### ISSUE TITLE
Sync UWP address meta with invoicing

### ISSUE THREAD

**Issue by picocodes** [AyeCode/invoicing#510]
**Is your feature request related to a problem? Please describe.**
UWP now uses a custom table to store a user's metadata. This prevents site admins from adding GetPaid related address fields on the UWP form builder.

**Describe the solution you'd like**
Work with UWP so that if any of the following fields is updated, it is also saved in the user meta table.

wpinv_country
wpinv_state
wpinv_city
wpinv_zip
wpinv_address
wpinv_phone
wpinv_company
wpinv_vat_number

**Comment by alexrollin** [comment]
+website 
+bio
+ first name 
+ last name

**Comment by wpdev10** [comment]
@picocodes How about giving account tab with the form containing the above fields and save them where Get paid is saving instead of giving in the account form? Something like we do for WooCommerce billing and shipping address. Customers might get confused to use the same key and also there needs to do a process to save fields in the user meta as UWP will save fields in the user_meta custom table.

**Comment by picocodes** [comment]
@wpdev10 yeah that's a better idea. Working on this now.

**Comment by picocodes** [comment]
Addressed https://github.com/AyeCode/invoicing/commit/0d18b89fbefbab635679c24f448ab2b3ad4fb075
