### ISSUE TITLE
Invoice payments

### ISSUE THREAD

**Issue by compito** [AyeCode/invoicing#566]
We need to have invoicing as payment type. That means that we create an invoice, and send link/pdf to customer. They than pay the invoice through their bank, and when we get the confirmation from bank that the invoice is paid we can go in and confirm their claim, membership payment or whatever. 
That's the most common way of paying for B2B services in Sweden/Scandinavia, and many other countries.

For that we need some other parameters than what we have in Bank Transfer type of payment. 

Bank information for example is not needed, all the BIC/Swift Code, etc. 
We use Bankgiro/Postgiro numbers, and that's the only information needed for payments. 

Also, it should support subscriptions, so the system should create new invoice and send it to user on end of every subscription period.
Can it be done? 

We were using Test Gateway to test the functionality initially, but those are marked as paid as soon as we go through payment process and it's not good. But creating a new Invoice Payment Gateway based on Test gateway could be fine. We just need some custom labels/text fields that will be created on invoices, and that the status is set to Awaiting payment after the payment process.

**Comment by picocodes** [comment]
Hi @compito,

We're working on a manual subscriptions addon that will add subscriptions functionality to Bank Transfer and all the other gateways that do not support recurring payments.

As for the BIC/Swift Code, etc, you can leave them blank in settings and they'll not appear on invoices and receipts. Also take a look at the [wpinv_bank_info](https://github.com/AyeCode/invoicing/blob/f9a8bbf16965480c705cfea70adaa1ccfcfd09a3/includes/gateways/class-getpaid-bank-transfer-gateway.php#L166) filter hook.

[You can create a new payment gateway](https://docs.wpgetpaid.com/article/550-creating-a-payment-gateway) based on the Test Gateway then set it to mark new invoices as pending payment instead of marking them as paid.
