### ISSUE TITLE
Set payment date without first having to mark the invoice as paid then saving it.

### ISSUE THREAD

**Issue by picocodes** [AyeCode/invoicing#694]

**Comment by eddiecrazy** [comment]
Hi,

I see this is marked as completed, but I still can't find this feature in the plugin, not working as expected.
I was aiming to issue invoices (all, including any future ones for the subscription) automatically at a certain date/time without needing to mark any of them paid. Just set a subscription, date and time for the first invoice and frequency of invoice issuing. Then, the system should issue any future invoice automatically at the designated date/time without needing the previous invoice to be marked as paid! 

Can this be something implemented, please? sometimes the customers aren't paying the invoice regularly and because of it, the next cycle (weekly or monthly) invoice it's not being generated!

Thank you
Eduard

**Comment by picocodes** [comment]
This is a different feature, please open a new issue so that we can track it

**Comment by eddiecrazy** [comment]
ok, fair enough.
I'll open as new

Thanks
Eduard
