### ISSUE TITLE
All notes are displayed as comments in admin side if plugin is deactivated.

### ISSUE THREAD

**Issue by gandhirk** [AyeCode/invoicing#70]
If invoicing plugin is not active then all the notes added to invoices or quotes are displayed as comments in admin side. The notes are not displayed if the plugin is active but when users will disable plugin they will see many comments which are actually our notes to the invoices or quotes. We have to either change the logic to store notes in comments or store notes in post/other tables.

Need your inputs.

Screenshots:
![comments-1](https://user-images.githubusercontent.com/22492841/29398520-c5d5e020-8342-11e7-93ff-23f632a08d9d.png)
![comments-2](https://user-images.githubusercontent.com/22492841/29398522-c7a8482a-8342-11e7-97f4-f39bc7a6bcf9.png)

**Comment by Stiofan** [comment]
DO you suggest we use our own table?

**Comment by mdrahul** [comment]
Actually, we should not use the custom table if not required. But we can go for it as well if no other solutions are there.

This issue is also there in case of WooCommerce plugin as well. They have a ticket open for WordPress core issue and once they will add a fix in core WordPress file then it will be solved.

**Comment by wpdev10** [comment]
No need to fix for now
